@CodedByKay.BondBridge.API_HostAddress = https://localhost:7277
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXl3aWJAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiNWIxZGJhMi03ODE3LTQ5NDUtYjY0Ni0yY2U1NjhiZmIxZGMiLCJyb2wiOiJjb21tb25fdXNlcl9hY2Nlc3MiLCJleHAiOjE3MDk1MzYyODksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcyNzciLCJhdWQiOiJjb20uY29kZWRieWtheS5ib25kYnJpZGdlLmNsaWVudCJ9.ZgAol1KiRIHj1Xe4eFwF7hatbi5PrgIjj19YvcgVQvA
@role = admin_access
@userId = b5b1dba2-7817-4945-b646-2ce568bfb1dc

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/adduser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "email": "kaywib@gmail.com",
  "password": "Rumpa2024!"
}
### 

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/addrole/{{role}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/addroletouser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}},
  "role": {{role}}
}
###

GET {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/ensurecreated HTTP/1.1
Authorization: Bearer {{accessToken}}

###

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/removerolefromuser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}},
  "role": {{role}}
}
###

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/deleteuser HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": {{userId}}
}


###

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/ApplicationManager/deleterole HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "role": {{role}}
}


###