@CodedByKay.BondBridge.API_HostAddress = https://localhost:7277
@refreshToken = <refreshToken>
@accessToken = <accessToken>
@customHeader = <header>


POST {{CodedByKay.BondBridge.API_HostAddress}}/api/Authentication/signin HTTP/1.1
CodedByKay-BondBridge-header: {{customHeader}}
Content-Type: application/json

{
  "email": "",
  "password": "",
  "isApp":true <-- Only use with app signin. When you need a new token for the app--
}
###

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/Authentication/refreshtoken HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json
CodedByKay-BondBridge-header: {{customHeader}}

{
  "accessToken": "{{accessToken}}",
  "refreshToken": "{{refreshToken}}"
}


### 