@CodedByKay.BondBridge.API_HostAddress = https://localhost:7277

GET {{CodedByKay.BondBridge.API_HostAddress}}/api/messages/get/0dbe474f-89ba-4c2c-bf58-c7e05eb60629
Accept: application/json

###

POST {{CodedByKay.BondBridge.API_HostAddress}}/api/Authentication/login HTTP/1.1
Content-Type: application/json

{
  "email": "kay@codedbykay.se",
  "password": "Rumpa2024!"
}
###

GET {{CodedByKay.BondBridge.API_HostAddress}}/api/Authentication/adminrequesttest HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXlAY29kZWRieWtheS5zZSIsInJvbCI6WyJhZG1pbl9hY2Nlc3MiLCJjb21tb25fdXNlcl9hY2Nlc3MiXSwiZXhwIjoxNzA5NDY2NTU5LCJpc3MiOiJDb2RlZEJ5S2F5LkJvbmRCcmlkZ2UiLCJhdWQiOiJDb2RlZEJ5S2F5LkJvbmRCcmlkZ2UuQ2xpZW50In0.sqSYDvVt5BWz4lWD_l7oCgGd3LHsxU62RsM0R4pQlts

###

GET {{CodedByKay.BondBridge.API_HostAddress}}/api/Authentication/userrequesttest HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrYXlAY29kZWRieWtheS5zZSIsInJvbCI6WyJhZG1pbl9hY2Nlc3MiLCJjb21tb25fdXNlcl9hY2Nlc3MiXSwiZXhwIjoxNzA5NDY2NTU5LCJpc3MiOiJDb2RlZEJ5S2F5LkJvbmRCcmlkZ2UiLCJhdWQiOiJDb2RlZEJ5S2F5LkJvbmRCcmlkZ2UuQ2xpZW50In0.sqSYDvVt5BWz4lWD_l7oCgGd3LHsxU62RsM0R4pQlts